# Generated by Django 5.2.8 on 2025-11-22 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="delete_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=None),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("enabled", "Enabled"),
                    ("disabled", "Disabled"),
                    ("deleted", "Deleted"),
                ],
                default="enabled",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
